---
title: "dartmouth_analysis"
output: html_document
date: "2022-10-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggthemes)
```

# psyrev data

```{r}
psyrev_switch = read_csv("data-psyrev_model_all_switch_all_switchresults.csv")
psyrev_similarity = read_csv("data-psyrev_model_all_switch_all_individualitemfits.csv") %>%
  select(Subject, Fluency_Item, Frequency_Value, Phonological_Similarity) %>%
  rename(semantic = Frequency_Value,
         phonological = Phonological_Similarity)
  
```
## switch methods
```{r}
psyrev_switch_sample = psyrev_switch %>% filter(Subject == 51 &
              Switch_Method %in% c("simdrop", "troyer", "delta_rise=0.0_fall=1.0",
                                   "multimodal_alpha=0.4") &
      Fluency_Item %in% c("aardvark", "elephant", "flea", "ferret", "parrot", "hippopotamus")) %>%
  mutate(prev = lag(Fluency_Item),
         pair = paste(prev, Fluency_Item, sep = "-")) %>%
  left_join(psyrev_similarity) %>%
  pivot_longer(names_to = "type", cols = c(semantic, phonological)) %>%
  group_by(Switch_Method) %>%
  mutate(row = row_number(),
         Switch_Method = fct_recode(Switch_Method, multimodal = "multimodal_alpha=0.4",
                                     delta = "delta_rise=0.0_fall=1.0",
                                     simdrop = "simdrop",
                                     troyer= "troyer"))%>%
  mutate(Switch_Method = fct_relevel(Switch_Method, "troyer","simdrop", "delta", "multimodal"),
         Switch_Value = ifelse(Switch_Value == 1, "switch", "cluster"))%>%
  filter(Fluency_Item != "aardvark") %>%
  rename(method = Switch_Method,
         transition = Switch_Value)


psyrev_switch_sample %>%
  ggplot(aes(x = row, y = value, group= type, color = type, label = pair)) +
  geom_line()+
  ggrepel::geom_text_repel(color = "black")+
  facet_wrap(~method)+
  scale_color_stata()+
  geom_point(aes(shape = transition), size = 4)+
  ggthemes::theme_few()+
  labs(x = "retrieval order", y = "similarity value")+
  theme(axis.title = element_text(face = "bold", size = rel(1)),
        strip.text= element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)))
  
  
```

## model fits

```{r}

psyrev_models = read_csv("data-psyrev_model_all_switch_all_modelresults.csv")

psyrev_sum_nLL = psyrev_models %>% group_by(Model) %>%
  filter(Model %in% c("forage_static", "forage_dynamic_simdrop", "forage_dynamic_troyer",
                      "forage_random_baseline")) %>%
  summarise(sum_nLL = sum(Negative_Log_Likelihood_Optimized)) %>%
  arrange(sum_nLL)
```



# dartmouth data
```{r}
dartmouth_modeldata = read_csv("dartmouth_T1_model_all_switch_all_modelresults.csv") %>% left_join(read_csv("dartmouth_code.csv")) %>%  filter(!is.na(group))


dartmouth_metrics = read_csv("dartmouth_T1_model_all_switch_all_individualitemfits.csv") %>% left_join(read_csv("dartmouth_code.csv"))%>%  filter(!is.na(group))

dartmouth_switch = read_csv("dartmouth_T1_model_all_switch_all_switchresults.csv") %>% left_join(read_csv("dartmouth_code.csv"))%>%  filter(!is.na(group))

```

## basic descriptives


```{r}
subjects = dartmouth_metrics %>% select(Subject, group) %>% distinct() %>% 
  group_by(group) %>% count()

metrics_long = dartmouth_metrics %>% select(Subject, group, Fluency_Item,
                   Semantic_Similarity, Phonological_Similarity,Frequency_Value) %>%
  rename(frequency = Semantic_Similarity, 
         semantic = Frequency_Value,
         phonological = Phonological_Similarity)%>%
  pivot_longer(names_to = "type", 
               cols=c(semantic, phonological,frequency)) %>%
  mutate(type = as.factor(type),
         group =as.factor(group))


sem =metrics_long %>%
    group_by(group, type) %>%
  summarise(ci = list(mean_cl_boot(value) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest %>%
    filter(type == "semantic") %>%
  ggplot(aes(x = type, y = mean, group = group, 
             fill = group)) +
         geom_bar(stat = "identity", position = "dodge", width = 0.7, color= "black")+
            geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.1, 
                color = "black", position = position_dodge(0.70))+
  theme_few()+
  scale_fill_calc()+
  scale_color_calc()+
  labs(y = "", x = "")+
  theme(aspect.ratio = 1)+
   theme(axis.title = element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)),
         legend.position = "none")

phon =metrics_long %>%
    group_by(group, type) %>%
  summarise(ci = list(mean_cl_boot(value) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest %>%
    filter(type == "phonological") %>%
  ggplot(aes(x = type, y = mean, group = group, 
             fill = group)) +
         geom_bar(stat = "identity", position = "dodge", width = 0.7, color= "black")+
            geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.1, 
                color = "black", position = position_dodge(0.70))+
  theme_few()+
  scale_fill_calc()+
  scale_color_calc()+
  labs(y = "", x = "beta")+
  theme(aspect.ratio = 1)+
   theme(axis.title = element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)),
         legend.position = "none")

freq =metrics_long %>%
    group_by(group, type) %>%
  summarise(ci = list(mean_cl_boot(value) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest %>%
    filter(type == "frequency") %>%
  ggplot(aes(x = type, y = mean, group = group, 
             fill = group)) +
         geom_bar(stat = "identity", position = "dodge", width = 0.7, color= "black")+
            geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.1, 
                color = "black", position = position_dodge(0.70))+
  theme_few()+
  scale_fill_calc()+
  scale_color_calc()+
  labs(y = "mean value", x = "")+
  theme(aspect.ratio = 1)+
   theme(axis.title = element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)),
         legend.position = "none")

gridExtra::grid.arrange(freq, phon, sem, nrow = 1)
  
library(lme4)
model = lmer(data = metrics_long %>% filter(type == "phonological"), 
           value ~ group + (1|Subject))
summary(model)
car::Anova(model)

```

## clusters and switches

```{r}
## count number of switches

switch_count = dartmouth_switch %>%
  filter(Switch_Value == 1) %>%
  group_by(Subject, Switch_Method, group) %>%
  count()

switch_count %>%
    group_by(group, Switch_Method) %>%
  summarise(ci = list(mean_cl_boot(n) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest %>%
  filter(Switch_Method %in% c("simdrop", "troyer")) %>%
  ggplot(aes(x = Switch_Method, y = mean, group = group, 
             fill = group)) +
         geom_bar(stat = "identity", position = "dodge", width = 0.7, color= "black")+
            geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.1, 
                color = "black", position = position_dodge(0.70))+
  theme_few()+
  scale_fill_calc()+
  scale_color_calc()+
  labs(y = "mean number of switches across groups")+
  theme(aspect.ratio = 1)+
   theme(axis.title = element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)))

## number of items in cluster

size_data = switch %>% 
  filter(Switch_Method %in% c("simdrop", "troyer")) %>%
  group_by(Subject, group, Switch_Method) %>%
    summarise(rl = list(rle(Switch_Value)), 
              switch_type = rl[[1]]$values, 
              num_items = rl[[1]]$lengths) %>% select(-rl)%>%
  arrange(Subject)

cluster_size = size_data %>%
  filter(switch_type == 0) %>%
  mutate(num_items= num_items+1)


cluster_size %>%
    group_by(group, Switch_Method) %>%
  summarise(ci = list(mean_cl_boot(num_items) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest %>%
  ggplot(aes(x = Switch_Method, y = mean, group = group, 
             fill = group)) +
         geom_bar(stat = "identity", position = "dodge", width = 0.7, color= "black")+
            geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.1, 
                color = "black", position = position_dodge(0.70))+
  theme_few()+
  scale_fill_calc()+
  scale_color_calc()+
  labs(y = "mean cluster size")+
  theme(aspect.ratio = 1)+
   theme(axis.title = element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)))



```

## betas

```{r}
betas = dartmouth_modeldata %>% select(Subject, group, Model, 
                               Beta_Frequency, Beta_Semantic, Beta_Phonological) %>%
  filter(Model %in% c("forage_static", "forage_dynamic_simdrop", "forage_dynamic_troyer")) %>%
    pivot_longer(names_to = "beta", 
               cols=c(Beta_Frequency, Beta_Semantic, Beta_Phonological)) %>%
  separate(beta, into = c("beta1", "beta")) %>% select(-beta1)



# phonological betas

phon_betas = modeldata %>% select(Subject, group, Model, 
                               Beta_Frequency, Beta_Semantic, Beta_Phonological) %>%
  filter(Model %in% c("forage_phonologicalstatic", 
                      "forage_phonologicaldynamicglobal_simdrop",
                      "forage_phonologicaldynamiclocal_simdrop",
                      "forage_phonologicaldynamicswitch_simdrop",
                      "forage_phonologicaldynamicglobal_troyer",
                      "forage_phonologicaldynamiclocal_troyer",
                      "forage_phonologicaldynamicswitch_troyer")) %>%
    pivot_longer(names_to = "beta", 
               cols=c(Beta_Frequency, Beta_Semantic, Beta_Phonological)) %>%
  separate(beta, into = c("beta1", "beta")) %>% select(-beta1)

betas %>%
  filter(!is.na(value)) %>%
  #filter(beta == "Phonological") %>%
    group_by(group, Model, beta) %>%
  summarise(ci = list(mean_cl_boot(value) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest %>%
  ggplot(aes(x = beta, y = mean, group = group, 
             fill = group)) +
         geom_bar(stat = "identity", position = "dodge", width = 0.7, color= "black")+
            geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.1, 
                color = "black", position = position_dodge(0.70))+
  theme_few()+
    facet_wrap(~Model)+
  scale_fill_calc()+
  scale_color_calc()+
  labs(y = "parameter value")+
  theme(aspect.ratio = 1)+
   theme(axis.title = element_text(face = "bold", size = rel(1)),
          legend.title = element_text(face = "bold", size = rel(1)),
         plot.title = element_text(hjust = .5),
         axis.text.x = element_text(face = "bold", size = rel(1.2)))

```



## model LLs
```{r}

sum_nLL = modeldata %>% group_by(group, Model) %>%
  #filter(Model %in% c("forage_static", "forage_dynamic_simdrop", "forage_dynamic_troyer")) %>%
  summarise(sum_nLL = sum(Negative_Log_Likelihood_Optimized)) %>%
  arrange(sum_nLL) %>%
  slice_min(sum_nLL)

```

